---
title: "Adventure for Dementia"
author: "Amy Whitehead"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

require(tidyverse)
require(sf)
require(XML)
require(lubridate)
require(showtext)
require(xkcd)
require(emojifont)
require(gganimate)
require(magick)
require(av)
require(paletteer)
require(patchwork)

animate <- gganimate::animate

this_month <- "July"

# options(gganimate.dev_args = list(fps = 10, start_pause = 5,end_pause = 5, res = 72, height = 20, units = "cm"))
```

```{r functions and constants}

font_add("xkcd", "data/xkcd.ttf")
showtext_auto()

caption_text <- "\nAn adventurous running challenge to raise money for Dementia Canterbury\nFollow my journey at www.facebook.com adventurefordementia.nz"

base_font <- 15

read_gpx <- function(gpx_file){
  # Parse the GPX file
  pfile <- htmlTreeParse(file = gpx_file, error = function(...) {
  }, useInternalNodes = T)
  # Get all elevations, times and coordinates via the respective xpath
  elevations <- as.numeric(xpathSApply(pfile, path = "//trkpt/ele", xmlValue))
  times <- xpathSApply(pfile, path = "//trkpt/time", xmlValue)
  coords <- xpathSApply(pfile, path = "//trkpt", xmlAttrs)
  
  # Extract latitude and longitude from the coordinates
  lats <- as.numeric(coords["lat",])
  lons <- as.numeric(coords["lon",])
  
  data.frame(lat = lats, lon = lons, elevation = elevations, time = times) %>% 
    st_as_sf(coords = c("lon","lat"),crs = 4136) 
  
}

make_monthly_repeats <- function(df, n){
 as.data.frame(lapply(df, rep, n)) %>% 
    mutate(month = n)
}

calculate_distance <- function(df){
  df %>% 
    mutate(lead_dist = geometry[row_number() + 1],
           dist = st_distance(geometry, lead_dist, by_element = T),
           lead_elevation = elevation[row_number() + 1],
           elevation_change = lead_elevation - elevation,
           cum_dist = as.numeric(cumsum(dist))/1000) %>% 
    # remove some funky elevation points
    filter(abs(elevation_change) < 6) %>% 
    mutate(uphill = case_when(elevation_change < 0 ~ 0,
                              TRUE ~ elevation_change),
           cum_uphill = as.numeric(cumsum(uphill)),
           Month = factor(month.name[month])
  )
}

plot_run <- . %>% 
  {ggplot(data = ., aes(cum_dist,elevation,colour = done)) +
      geom_line(show.legend = FALSE) +
      theme_classic(base_size = base_font) +
      labs(subtitle = "Elevation in m",
           x = "Distance in km",
           y = NULL,
           title = "Adventure for\nDementia",
           caption = caption_text) +
      coord_cartesian(expand = FALSE,clip = "off") +
      scale_y_continuous(breaks = c(100,200, 300)) +
      # scale_x_continuous(limits = c(0,68)) +
      theme(strip.background = element_blank(),
            strip.text.y = element_blank(),
            plot.subtitle = element_text(hjust = -0.025),
            plot.title = element_text(hjust = 1,size = 30,vjust = -40),
            plot.caption = element_text(size = rel(0.85)),
            plot.margin = margin(-60,10,5,5),
            text=element_text(family="xkcd"),
            axis.text = element_text(color = "black",size = rel(0.85))) }

calculate_elapsed_time <- function(df){
  df %>% 
    mutate(date_time = parse_date_time(time,tz = "UTC",orders = "%Y-%m-%d%H:%M%S" ) %>% 
             with_tz("Pacific/Auckland"),
           elapsed_time = as.numeric(date_time - min(date_time,na.rm=T)),
           hours = hour(seconds_to_period(elapsed_time)),
           minutes = minute(seconds_to_period(elapsed_time)),
           hours_minutes = hm(paste(hours,minutes, sep=":")),
           month = month(date_time))
}

```


```{r load data}
pop_track <- st_read("data/pipeline-of-pain.gpx",layer = "tracks")

pop_points <- st_read("data/pipeline-of-pain.gpx",layer = "track_points")

pop_track <- st_read("data/The_Pipeline_of_Pain_Strava.gpx",layer = "tracks")

pop_points <- st_read("data/The_Pipeline_of_Pain_Strava.gpx",layer = "track_points")


# gpx_file <- "data/The_Pipeline_of_Pain_Strava.gpx"
gpx_file <- "data/pipeline-of-pain.gpx"


pop <- read_gpx(gpx_file)

pop_repeats <- map_dfr(1:12,function(x) make_monthly_repeats(pop,x)) %>% 
  group_by(month) %>% 
  calculate_distance() %>% 
  # # remove some funky elevation points
  # filter(abs(elevation_change) < 6) %>% 
  # add column to indicate it's been run
  mutate(done = case_when(Month %in% 
                            month.name[c(1:which(this_month == month.name))] ~ TRUE,
                          TRUE ~ FALSE)) %>% glimpse
  
month_labels <- pop_repeats %>% 
  filter(cum_dist == max(cum_dist)) %>% 
  # add column to indicate it's been run
  mutate(emoji = case_when(isTRUE(done)~ emoji("running_woman"),
                          TRUE ~ NA_character_)) %>% 
  ungroup %>% 
  select(Month, cum_dist, done,emoji) %>% glimpse



monthly_effort_files <- dir("data/monthly_efforts/",pattern = "gpx$",full.names = T)

monthly_efforts <- map_df(monthly_effort_files,
                        function(x) read_gpx(x) %>% 
                          mutate(Month = factor(gsub("data/monthly_efforts/Adventure_for_Dementia_|\\.gpx","",x),
                                 levels = month.name))) %>% 
filter(Month %in% month.name[1:which(this_month == month.name)]) %>% 
  group_by(Month) %>% 
  calculate_elapsed_time() %>% 
  calculate_distance %>% 
  na.omit() %>% 
  st_drop_geometry %>% glimpse


```

```{r make plots}
all_months <- pop_repeats %>% 
  ungroup %>% 
  plot_run() +
  geom_text(data = month_labels,
            aes(y = 250, x = cum_dist + 1 ,label = Month),
            hjust = 0,
            family="xkcd",
            size = base_font * 0.36,
            show.legend = FALSE) +
      facet_grid(Month~.) +
  scale_x_continuous(limits = c(0,72)) +
  scale_colour_manual(values = c("black","black"))

ggsave(all_months,file = "outputs/elevation_all.png",dpi=72,width = 20, height = 20, units = "cm")  

# all_months +
#   labs(caption = NULL) +
#   theme(plot.background = element_rect(fill = "transparent"),
#         panel.background = element_rect(fill = "transparent"),
#         plot.title = element_text(hjust = 1,size = 30,vjust = -40, colour = "transparent"))

ggsave(all_months +
  labs(caption = NULL) +
  theme(plot.background = element_rect(fill = "transparent", colour = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        plot.title = element_text(hjust = 1,size = 30,vjust = -40, colour = "transparent")),
  file = "outputs/elevation_all_poster.png",dpi=72,width = 20, height = 20, units = "cm")
  
progress <- all_months + 
  scale_colour_manual(values = c("black","red")) +
  geom_text(data = month_labels,
            aes(y = 300, x = cum_dist + 11 ,label = emoji),
            hjust = 0,
            family="EmojiOne",
            size = 5,
            show.legend = FALSE)

ggsave(progress,file = paste0("outputs/",this_month,"/elevation_progress.png"),
       dpi=72,width = 20, height = 20, units = "cm")  

# make individual plots for each month
walk(month.name, function(x){
  
  pop_repeats %>% 
  ungroup %>% 
  filter(Month %in% x) %>% 
  plot_run() +
  geom_label(data = month_labels %>% 
              filter(Month %in% x),
            aes(y = 250, x = cum_dist - 0.25 ,label = Month),
            hjust = 1,
            family="xkcd",
            size = base_font * 0.36,
            show.legend = FALSE,label.size = NA) +
  scale_colour_manual(values = c("black","black"))
  

 ggsave(file = paste0("outputs/",x,"/elevation.png"),dpi=72,width = 20, height = 20, units = "cm")
})


event_plot <- pop_repeats %>% 
  ungroup %>% 
  filter(Month %in% this_month) %>% 
  plot_run() +
  # geom_text(data = month_labels %>% 
  #             filter(Month %in% this_month),
  #           aes(y = 225, x = cum_dist/2 ,label = Month),
  #           # hjust = 1,
  #           family="xkcd",
  #           size = base_font*2,
  #           show.legend = FALSE) +
  scale_colour_manual(values = c("black","black")) +
  labs(caption = NULL) +
  theme(plot.title = element_text(hjust = 1,size = 30,vjust = -50),
        plot.subtitle = element_text(hjust = -0.025,vjust = -0.5,size = rel(1.5)),
        plot.background = element_rect(fill = "transparent", colour = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        axis.text = element_text(color = "black",size = rel(1.5)),
        axis.title.x = element_text(size = rel(1.5))) 
  

 ggsave(event_plot,
        file = paste0("outputs/",this_month,"/elevation_wide.svg"),width = 30, height = 15, units = "cm")
 ggsave(event_plot,
        file = paste0("outputs/",this_month,"/elevation_square.svg"),width = 15, height = 15, units = "cm")
 
 ggsave(event_plot + 
          theme(plot.title = element_text(hjust = 1,size = 30,vjust = -50,colour = "transparent")), 
        file = paste0("outputs/",this_month,"/elevation_race_number.svg"),width = 17, height = 17*0.7, units = "cm")
 
# ragg::agg_png("outputs/",this_month,"/elevation_wide.png", width = 30, height = 15, units = "cm", res = 150, scaling = 3,background="transparent")
# event_plot
# dev.off() 
```

```{r stair plot}

stairs <- data.frame(lap = seq(1:79),
           Month = c("January","January",rep("February",2),rep("March",3),rep("April",4),rep("May",5),rep("June",6),
                     rep("July",7),rep("August",8),rep("September",9),rep("October",10),rep("November",11),
                     rep("December",12))) %>% 
  left_join(month_labels) %>% 
  group_by(Month) %>% 
  mutate(month = which(month.name == Month),
         spacing = 1/month) %>% 
  ungroup() %>% 
  mutate(lap_distance = c(0,rep(5.06,78)),
         cum_lap_distance = cumsum(lap_distance),
         cum_spacing = cumsum(spacing)) %>% 
  
ggplot(aes(cum_spacing,lap, colour = done)) +
  geom_hline(yintercept = c(1,3,6,10,15,21,28,36,45,55,66,78),colour = "lightgrey",linetype = "dotted") +
  geom_vline(xintercept =1:12,colour = "lightgrey",linetype = "dotted") +
  geom_step(colour = "black") +
  geom_step(data = . %>% filter(done),colour = "red") +
  geom_text(data = . %>% 
              filter(done) %>% 
              filter(cum_spacing == max(cum_spacing)),
            aes(cum_spacing,lap,label = emoji),
            hjust = 0.9,
            vjust = 0,
            family="EmojiOne",
            size = 30,
            show.legend = FALSE)+
  labs(x = NULL,
       y = "Number of laps") +
  theme_classic(base_size = base_font) +
      labs(subtitle = "Number of laps",
           x = NULL,
           y = NULL,
           title = "Adventure for\nDementia") +
      coord_cartesian(expand = FALSE,clip = "off") +
      scale_y_continuous(limits = c(0,80)) +
      scale_x_continuous(limits=c(1,13),breaks=0:12,labels = c("",month.abb)) +
      theme(plot.background=element_rect(fill="white"),
        panel.grid=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key=element_rect(fill="white"),
        legend.spacing.x = unit(0.075, 'cm'),
        text=element_text(family="xkcd",size = 30),
        axis.text= element_text(color = "black"),
        plot.caption = element_text(lineheight = 0.25),
        plot.title = element_text(hjust = 0.95,size = 80,vjust = -40,lineheight = 0.25),
        plot.title.position = "plot",
        plot.subtitle = element_text(hjust = 0,lineheight = 0.25),
        plot.margin = margin(-40,5,5,5)) 
  
ggsave(stairs,file = paste0("outputs/",this_month,"/stairs.png"),width = 12, height = 12, units = "cm")

```



```{r animated plots}


animated_plot <- monthly_efforts %>% 
  # hack for colour plotting
  rename(done = Month) %>% 
  mutate(this_month = case_when(done %in% this_month ~TRUE,
                                TRUE ~ FALSE)) %>% 
  plot_run() +
   geom_point(aes(alpha = this_month),size=4) +
  # geom_text(aes(label = done),size = 10) +
  theme(plot.title = element_text(vjust = -10)) +
  transition_reveal(elapsed_time) +
  labs( subtitle = 'Time: {round(frame_along/60/60,1)} hours',
       caption = NULL,
       colour = NULL,
       title = "Adventure for\nDementia",
       y = "Elevation in m") +
  theme(legend.position = "bottom",
        legend.direction = "horizontal") +
  scale_colour_paletteer_d(palette = "rcartocolor::Vivid") +
  scale_alpha_manual(values = c("FALSE"=0.5, "TRUE"=1),guide = 'none') #Bold
  

animated_plot_gif <- gganimate::animate(animated_plot,
                                        res = 72, width = 20, height = 20, units = "cm",
                                        fps = 10, detail = 10, start_pause = 5, end_pause = 10)

anim_save(animated_plot_gif,filename = paste0("outputs/",this_month,"/animated_plot.gif"))

animated_plot_mp4 <- gganimate::animate(animated_plot,
                                    res = 150, width = 15, height = 15, units = "cm",
                                    fps = 7, detail = 7, start_pause = 7, end_pause = 10,
                                    renderer = av_renderer())

anim_save(animated_plot_mp4,filename = paste0("outputs/",this_month,"/animated_plot.mp4"))


```

```{r calculate sunrise-sunset}

require(suncalc)

convert_time <- function(time) as.numeric(format(time,"%H%M"))

time_format <- function(hrmn) substr(sprintf("%04d", hrmn),1,2)


# get first Saturday of month
x <- seq(as.Date("2023-01-01"), as.Date("2023-12-31"), by = "day")
# You need to adapt "Monday" to the equivalent in your locale
rundays <- x[weekdays(x) == "Saturday" & as.numeric(format(x, "%d")) <= 7]
names(rundays) <- month.name

actual_run_times <- monthly_efforts %>% 
  group_by(Month,month) %>% 
  summarise(start = min(date_time),
            end = max(date_time),
            duration = end - start,
            done = TRUE) %>% 
  mutate(mean_lap_time = duration / month)

daylight_hours <- getSunlightTimes(x,lat = -43.5, lon = 172.6, tz = "Pacific/Auckland",
                 keep = c("dawn","sunrise","sunset","dusk")) %>% 
  mutate(month = month(date),
         daylight = dusk - dawn,
         sunlight = sunset - sunrise) %>% #,
         # across(c("dawn","sunrise","sunset","dusk"),~format(.,"%H%M"))) %>% glimpse
  left_join(actual_run_times) %>% 
  mutate(mean = case_when(is.na(duration) ~ 
                                          as.duration(month * max(mean_lap_time,na.rm = T)),
                                        TRUE ~ duration),
         max = case_when(is.na(duration) ~ as.duration(month*3600 * 1.5),
                                        TRUE ~ duration),
         start_dawn = case_when(is.na(start) ~ dawn,
                           TRUE ~ start),
         start_sunrise = case_when(is.na(start) ~ sunrise,
                           TRUE ~ start),
         done = case_when(is.na(done) ~ FALSE,
                          TRUE ~ TRUE)) %>% 
  pivot_longer(names_to = "lap_time",
               values_to = "expected_time",
               cols= one_of(c("mean","max"))) %>% 
  mutate(lap_time = factor(case_when(done ~ "actual",
                                     TRUE ~ lap_time),
                           levels = c("actual","mean","max"))) %>% 
  glimpse

daylight_pal <- c(daylight = "#F7E690FF",
                  night = "#172869FF",
                  actual = "#088BBEFF",
                  estimate = "#1BB6AFFF")


daylight_labels <- data.frame(class = c("actual", "mean", "max"),
                              values = c(alpha(daylight_pal[[3]], 1),
                                         alpha(daylight_pal[[4]], 1),
                                         alpha(daylight_pal[[4]], 0.5)),
                              labels = c("Actual run time",
                                         paste0("Mean lap pace = ",
                                                round(max(actual_run_times$mean_lap_time),1) ," hours"),
                                         "Max lap pace = 1.5 hours"))


plot_daylight_hours <- ggplot(data = daylight_hours,
       aes(x= date)) +
   geom_point(data = data.frame(date = daylight_hours$date,time = runif(length(daylight_hours$date))*2400),
             aes(date,time),colour = "white",shape = ".") +
  geom_ribbon(aes(ymin = convert_time(sunrise),
                  ymax = convert_time(sunset)), 
              fill=daylight_pal[1]) + 
  geom_ribbon(aes(ymin = convert_time(dawn),
                  ymax = convert_time(dusk)),
              alpha = 0.5, fill=daylight_pal[1]) +

  geom_linerange(data = daylight_hours %>% 
                   filter(date %in% rundays | date %in% as.Date("2023-04-02")), 
                 aes(ymin = convert_time(start_dawn), 
                     ymax = convert_time(start_dawn + expected_time),
                     colour = lap_time),
                 lwd = 4,show.legend = TRUE) +
  scale_x_date(expand=c(0,0),date_breaks = "month",date_labels = "%b") +
  scale_y_continuous( limits=c(0,2400),labels = time_format, 
                     breaks=seq(0, 2400, 300), expand=c(0,0)) + 
  theme(panel.background=element_rect(fill=daylight_pal[2]),
        panel.grid=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key=element_rect(fill="white")) +
  labs (x = NULL,
        y = NULL,
        colour = NULL,
        subtitle = "Time of day") +
  scale_colour_manual(name = "Time to complete",
                      values = daylight_labels$values,
                      labels = daylight_labels$labels)


plot_daylength <- ggplot(data = daylight_hours,
       aes(x= date)) +
  geom_point(data = data.frame(date = daylight_hours$date,time = runif(length(daylight_hours$date))*24),
             aes(date,time),colour = "white",shape = ".") +
  geom_ribbon(aes(ymin = 0,ymax = sunlight), fill=daylight_pal[1]) + 
  geom_ribbon(aes(ymin = 0,ymax = daylight),alpha = 0.5, fill=daylight_pal[1]) +
  geom_linerange(data = daylight_hours %>%
                   filter(date %in% rundays | date %in% as.Date("2023-04-02")),
                 aes(ymin = 0, ymax = as.numeric(expected_time)/3600,
                     colour = lap_time),
                 lwd = 4) +
  scale_x_date(expand=c(0,0),date_breaks = "month",date_labels = "%b") +
  scale_y_continuous(limits=c(0,24), 
                     breaks=seq(0, 24, 3), expand=c(0,0)) +
  theme(panel.background=element_rect(fill=daylight_pal[2]),
        panel.grid=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key=element_rect(fill="white")) +
  labs (x = NULL,
        y = NULL,
        subtitle  = "Number of daylight hours",
        colour = "Expected lap time") +
  scale_colour_manual(name = "Time to complete",
                      values = daylight_labels$values,
                      labels = daylight_labels$labels)

combined_daylight_plot <- (plot_daylight_hours +
  theme(axis.text.x = element_blank())) / plot_daylength +
  plot_annotation(caption = "The time taken to complete each month's Adventure for Dementia plotted against the available daylight hours.\nGreen bars show estimated times based on current pacing.",
                  # subtitle = "Will I be running in the dark?",
                  title = "Adventure\nfor Dementia") +
  plot_layout(guides = 'collect') &
  theme(panel.background=element_rect(fill=daylight_pal[2]),
        panel.grid=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key=element_rect(fill="white"),
        legend.spacing.x = unit(0.15, 'cm'),
        text=element_text(family="xkcd",size = 30),
        axis.text= element_text(color = "black"),
        plot.caption = element_text(lineheight = 0.25),
        plot.title = element_text(hjust = 1,size = 50,vjust = -20,lineheight = 0.25),
        plot.subtitle = element_text(hjust = 0,lineheight = 0.25),
        plot.margin = margin(-10,10,5,5))

ggsave(combined_daylight_plot,
       filename = "outputs/running_in_the_dark.png",width = 15, height = 15,units="cm")


ggsave(plot_daylength +
         labs(title = "Adventure\nfor Dementia") +
         theme(panel.background=element_rect(fill=daylight_pal[2]),
               panel.grid=element_blank(),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key=element_rect(fill="white"),
               legend.spacing.x = unit(0.075, 'cm'),
               text=element_text(family="xkcd",size = 30),
               axis.text= element_text(color = "black"),
               plot.caption = element_text(lineheight = 0.25),
               plot.title = element_text(hjust = 1,size = 50,vjust = -20,lineheight = 0.25),
               plot.subtitle = element_text(hjust = 0,lineheight = 0.25),
               plot.margin = margin(-10,10,5,5)),
       filename = "outputs/daylength.png",width=12, height = 12,units = "cm")

ggsave(plot_daylight_hours +
         labs(title = "Adventure\nfor Dementia") +
         theme(panel.background=element_rect(fill=daylight_pal[2]),
               panel.grid=element_blank(),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key=element_rect(fill="white"),
               legend.spacing.x = unit(0.075, 'cm'),
               text=element_text(family="xkcd",size = 30),
               axis.text= element_text(color = "black"),
               plot.caption = element_text(lineheight = 0.25),
               plot.title = element_text(hjust = 1,size = 50,vjust = -20,lineheight = 0.25),
               plot.subtitle = element_text(hjust = 0,lineheight = 0.25),
               plot.margin = margin(-10,10,5,5)),
       filename = "outputs/daylight_hours.png",width=12, height = 12,units = "cm")


```



```{r mountain elevation plot}

mountain_elevations <- readRDS("data/mountain_elevations.rds")

monthly_efforts %>% group_by(Month) %>% 
  summarise(vert = max(cum_uphill)) %>% 
  group_by(Month) %>% 
  mutate(mountain_elevations[which( mountain_elevations$metres <= vert),] %>% slice(1),
         nz_peaks[which( nz_peaks$metres <= vert),] %>% slice(1))

mountain_elevations %>% filter(str_detect(location_and_notes,"New Zealand|NZ"))

afd_elevation <- data.frame(Month = factor(month.name[1:7]),
           elevation = c(480,957,1431,1897,2394,2872,3338),
           mountain_height = c(487,959,1429,1895,2373,2882,3309),
           mountain = c("Mangatangi","Pirongia","Woolshed Hill","Ben Cruachan","Watch Tower","Grey Peak","Mt Vancouver"),
           url = c("https://www.topomap.co.nz/NZTopoMap/nz7737/Mangatangi/Waikato",
                   "https://www.topomap.co.nz/NZTopoMap/nz57002/Pirongia/Waikato",
                   "https://www.topomap.co.nz/NZTopoMap/nz33644/Woolshed-Hill/Canterbury",
                   "https://www.topomap.co.nz/NZTopoMap/nz17913/Ben-Cruachan/Otago",
                   "https://www.topomap.co.nz/NZTopoMap/nz26020/Watch-Tower/Canterbury",
                   "https://www.topomap.co.nz/NZTopoMap/nz26456/Grey-Peak/Canterbury",
                   "https://www.topomap.co.nz/NZTopoMap/nz26266/Mount-Vancouver/Canterbury")) %>% 
  left_join(month_labels) %>% 
  mutate(Month = factor(Month, levels = month.name),
         y = 1:7)


make_mountain <- function(N,elevation,distance){
  x <- c(sort(qnorm(runif(N/2, pnorm(-0.5), pnorm(0.5)))),sort(qnorm(runif(N/2, pnorm(-0.5), pnorm(0.5))),decreasing = T))
  data.frame(elevation = (x-min(x))/(max(x)-min(x))*(elevation-0),
             distance = seq(0,distance,length.out = N))
}

map_df(1:nrow(afd_elevation),function(x) make_mountain(elevation = afd_elevation$elevation[x],
                                                       distance = afd_elevation$cum_dist[x],
                                                       N = ceiling(afd_elevation$cum_dist[x]) * 10) %>% 
         mutate(Month = afd_elevation$Month[x],
                y = x)) %>% 
  # filter(Month %in% "January") %>% 
  ggplot(aes(x = distance,y = -y, group = Month,height = elevation,fill = elevation))+
  geom_density_ridges_gradient( show.legend = F,stat = "identity") + #, fill = "darkgreen"
  geom_text(data = afd_elevation, 
            aes(y = c(-0.5:-6.5),x =cum_dist - 2, label = paste0(mountain," - ",mountain_height," m")),
            size = 10,hjust=0,
            family = "xkcd") +
  scale_y_continuous(breaks = c(-1:-7),labels = afd_elevation$Month) + 
  scale_fill_paletteer_c("ggthemes::Green",direction = -1) + #"grDevices::terrain.colors"
  theme_minimal() +
  coord_cartesian(clip = "off") + 
  labs(y = NULL,
       x = "Distance in km",
       title = "Adventure for\nDementia") +
  theme(plot.background=element_rect(fill="white"),
        panel.grid=element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key=element_rect(fill="white"),
        legend.spacing.x = unit(0.075, 'cm'),
        text=element_text(family="xkcd",size = 30),
        axis.text= element_text(color = "black"),
        plot.caption = element_text(lineheight = 0.25),
        plot.title = element_text(hjust = 1.25,size = 80,vjust = -40,lineheight = 0.25),
        plot.title.position = "plot",
        plot.subtitle = element_text(hjust = 0,lineheight = 0.25),
        plot.margin = margin(-30,60,5,5)) 
  


ggsave(filename = "outputs/mountain_elevations.png",width=12, height = 12,units = "cm")

```

```{r , eval = FALSE}

require(terra) # for raster data
require(tidyterra) # for plotting rasters
# require(ggspatial) # for map annotations
require(maptiles) # for map backgrounds

tile_z11 <- get_tiles(st_bbox(st_buffer(st_transform(pop_track,3857),400)),
                       provider = "Stamen.Terrain",#"Esri.WorldTopoMap",#OpenTopoMap",#Stamen.Terrain",
                      crop = TRUE, zoom = 15)

pop_map <- pop_track %>% #read_gpx("data/monthly_efforts/Adventure_for_Dementia_January.gpx") %>% 
  ggplot() +
  geom_spatraster_rgb(data = tile_z11) +
  geom_sf(size = 1.5, colour = "grey30") +
  theme_void() 

ggsave(pop_map,file = "outputs/route_map.png")
  
# january_map <- afd_january %>% 
#   bind_cols(st_coordinates(afd_january)) %>% 

ggplot(aes(X,Y)) +
  geom_spatraster_rgb(data = tile_z11) +
  geom_line(size = 1, colour = "black") +
  theme_void() + 
  theme(text=element_text(family="xkcd"),
        plot.background = element_rect(fill = "white")) +
  # transition_reveal(diff_time) +
  labs(title = "Adventure for Dementia",
       subtitle = 'Time since start: {round(frame_along/60,0)} minutes',
       caption = NULL,
       fill = NULL,
       shape = NULL)

animate_january_map <- gganimate::animate(january_map,fps = 10,start_pause = 5, end_pause = 5,
                                          height = 20, units = "cm",res=72)

anim_save(animate_january_map,filename = "outputs/january_map_animation.gif")
```

https://towardsdatascience.com/how-to-combine-animated-plots-in-r-734c6c952315

```{r join animations together, eval = FALSE}

library(magick)
a_mgif <- image_read("outputs/january_map_animation.gif")
b_mgif <- image_read("outputs/january_animation.gif")

image_info(a_mgif)

new_gif <- image_append(c(a_mgif[1], b_mgif[1]), stack = FALSE)
for(i in 2:100){
  combined <- image_append(c(a_mgif[i], b_mgif[i]), stack = FALSE)
  new_gif <- c(new_gif, combined)
}


image_write(new_gif, "outputs/january_combined_animation.gif")
```


```{r xkcd stickman, eval = FALSE}
xrange <- range(pop_repeats$cum_dist,na.rm= T)
yrange <- range(pop_repeats$elevation,na.rm=T)
ratioxy <- diff(xrange) / diff(yrange)
 
mapping <- aes(x=x,
               y=y,
               scale=scale,
               ratioxy=ratioxy,
               angleofspine = angleofspine,
               anglerighthumerus = anglerighthumerus,
               anglelefthumerus = anglelefthumerus,
               anglerightradius = anglerightradius,
               angleleftradius = angleleftradius,
               anglerightleg =  anglerightleg,
               angleleftleg = angleleftleg,
               angleofneck = angleofneck)
 
dataman <- data.frame( x= c(5), y=c(100),
                  scale = c(10),
                  ratioxy = ratioxy,
                  angleofspine =  -pi / 2,#seq(- pi / 2, -pi/2 + pi/8, l=3) ,
                  anglerighthumerus = -pi/6,
                  anglelefthumerus = pi + pi/6,
                  anglerightradius = 0,
                  angleleftradius = runif(1,- pi/4, pi/4),
                  angleleftleg = 3*pi/2  + pi / 12 ,
                  anglerightleg = 3*pi/2  - pi / 12,
                  angleofneck = runif(1, min = 3 * pi / 2 - pi/10 , max = 3 * pi / 2 + pi/10))
 
january + xkcdman(mapping,dataman)
# }

```

```{r rayshader animated map, eval = FALSE}
# devtools::install_github("zappingseb/rayshaderanimate")
## This code currently doesn't work
require(rayshaderanimate)

test <- get_table_from_gpx(gpx_file) %>% 
  get_enriched_gpx_table()

test_bbox <- get_bbox_from_gpx_table(test)
el_mat <- get_elevdata_from_bbox(test_bbox)
elmat_rayshade <- el_mat %>% unlabel_elevdata()
el_mat_long <- get_elevdata_long(el_mat)

# data(el_mat) # load pre-stored data
# elmat_rayshade <- el_mat %>% unlabel_elevdata()
# elmat_long <- get_elevdata_long(el_mat)

plot_2d_elevdata(elevdata_rayshade = elmat_rayshade)
```

